### PR TITLE
Use postcss-initial to replace initial values in output

### PR DESCRIPTION
**Pull request by johnbender**
Hidden behind a new option `postcss`.

### CODE REVIEW

**Comment by jefflembeck** [comment]
:+1: major version bump though.

**Comment by johnbender** [comment]
> major version bump though

Oh? It's only adding a feature, everything else should be backward compatible since it's behind an option. I thought that meant a minor version bump?

**Comment by jefflembeck** [comment]
Woop, missed the whole "it's an option" thing. Perfect.

**Comment by johnbender** [comment]
@jefflembeck 

Yay!

**Pull request merged**
